const CLIENT_ID = "f9b69808a4f64f299c26b42bbe1c80ef";
const REDIRECT_URI = window.location.origin + window.location.pathname;
const SCOPES = "user-read-currently-playing user-read-playback-state user-modify-playback-state";
const API_BASE = "https://api.spotify.com/v1";

const $ = (selector) => document.querySelector(selector);
const state = { token: sessionStorage.getItem("airwave_token"), expiresAt: Number(sessionStorage.getItem("airwave_expires") || 0), verifier: null, lastTrack: null, progress: 0, duration: 0, isPlaying: false, timer: null, meet: { roomId: null, roomName: null, hostId: null, isHost: true, memberId: crypto.randomUUID(), memberName: `Guest ${Math.floor(Math.random() * 90 + 10)}`, members: {}, messages: [] } };
let meetChannel;

function base64Url(bytes) { return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
async function sha256(value) { return crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); }
function randomString(length) { const bytes = new Uint8Array(length); crypto.getRandomValues(bytes); return base64Url(bytes); }

async function connect() {
  if (state.meet.roomId && !state.meet.isHost) { setStatus("Only the room host needs to connect Spotify.", "error"); return; }
  if (CLIENT_ID === "YOUR_SPOTIFY_CLIENT_ID") { setStatus("Add your Spotify Client ID in app.js", "error"); return; }
  state.verifier = randomString(64); sessionStorage.setItem("airwave_verifier", state.verifier);
  const challenge = base64Url(await sha256(state.verifier)); const authState = randomString(24); sessionStorage.setItem("airwave_state", authState);
  const params = new URLSearchParams({ client_id: CLIENT_ID, response_type: "code", redirect_uri: REDIRECT_URI, scope: SCOPES, state: authState, code_challenge_method: "S256", code_challenge: challenge });
  window.location.assign(`https://accounts.spotify.com/authorize?${params}`);
}

async function finishLogin() {
  const params = new URLSearchParams(window.location.search); const code = params.get("code");
  if (!code) return;
  if (params.get("state") !== sessionStorage.getItem("airwave_state")) throw new Error("Spotify authorization state did not match.");
  const verifier = sessionStorage.getItem("airwave_verifier"); const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: CLIENT_ID, grant_type: "authorization_code", code, redirect_uri: REDIRECT_URI, code_verifier: verifier }) });
  if (!response.ok) throw new Error("Spotify could not finish the connection.");
  const data = await response.json(); storeToken(data); window.history.replaceState({}, "", REDIRECT_URI); window.location.hash = "connected";
}
function storeToken(data) { state.token = data.access_token; state.expiresAt = Date.now() + (data.expires_in * 1000) - 60000; sessionStorage.setItem("airwave_token", state.token); sessionStorage.setItem("airwave_expires", state.expiresAt); }
async function api(path, options = {}) { if (!state.token || Date.now() > state.expiresAt) throw new Error("Your Spotify session expired. Reconnect to continue."); const headers = { Authorization: `Bearer ${state.token}` }; if (options.body) headers["Content-Type"] = "application/json"; const response = await fetch(API_BASE + path, { ...options, headers }); if (response.status === 204) return null; if (response.status === 401) throw new Error("Your Spotify session expired. Reconnect to continue."); if (response.status === 403) throw new Error("Spotify playback control needs a Premium account and an active device."); if (!response.ok) throw new Error("Spotify playback is unavailable right now."); return response.json(); }

async function refreshPlayback() {
  if (!state.token) return; setStatus("Scanning the airwaves...");
  try { const [playing, queue] = await Promise.all([api("/me/player/currently-playing"), api("/me/player/queue")]); updateTrack(playing); updateQueue(queue); } catch (error) { setStatus(error.message, "error"); }
}
function updateTrack(data) {
  if (!data || !data.item || data.item.type !== "track") { $("#track-title").textContent = "Nothing is playing yet"; $("#track-artist").textContent = "Start a song in Spotify and refresh the dial."; $("#track-album").textContent = ""; $("#radio-track-title").textContent = "AIRWAVE FM"; $("#radio-track-artist").textContent = "READY FOR A SIGNAL"; setStatus("Waiting for a signal"); return; }
  const track = data.item; state.progress = data.progress_ms || 0; state.duration = track.duration_ms || 0; state.isPlaying = Boolean(data.is_playing); state.lastTrack = track.id; const artists = track.artists.map((artist) => artist.name).join(", "); $("#track-title").textContent = track.name; $("#track-artist").textContent = artists; $("#radio-track-title").textContent = track.name; $("#radio-track-artist").textContent = artists; $("#track-album").textContent = track.album.name; $("#device-name").textContent = data.device?.name || "Spotify device"; $("#album-art").innerHTML = track.album.images?.[0] ? `<img src="${track.album.images[0].url}" alt="${track.album.name} album artwork">` : '<span class="album-placeholder">&#9835;</span>'; $("#connection-label").textContent = "ON AIR"; document.body.classList.add("connected"); setStatus(state.isPlaying ? "Now transmitting" : "Paused in Spotify", "success"); updateProgress(); meetPublishTrack(); }
function updateQueue(data) { const item = data?.queue?.[0]; $("#next-track").textContent = item ? `Next up: ${item.name} / ${item.artists?.[0]?.name || "Unknown artist"}` : "Next up: queue is empty"; }
function updateProgress() { const percent = state.duration ? Math.min(100, (state.progress / state.duration) * 100) : 0; $("#progress-bar").style.width = `${percent}%`; $("#track-time").textContent = `${formatTime(state.progress)} / ${formatTime(state.duration)}`; }
function formatTime(ms) { const seconds = Math.floor(ms / 1000); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }
function setStatus(message, type = "idle") { $("#status-message").textContent = message; $("#status-message").style.color = type === "error" ? "var(--rust-dark)" : type === "success" ? "var(--green)" : ""; }
function tick() { if (state.isPlaying && state.progress < state.duration) { state.progress += 250; updateProgress(); } }
async function controlPlayback(action) { if (!state.token) { setStatus("Connect Spotify before controlling playback.", "error"); return; } try { setStatus("Sending command..."); const endpoint = action === "play" ? "/me/player/play" : action === "pause" ? "/me/player/pause" : `/me/player/${action}`; await api(endpoint, { method: action === "play" || action === "pause" ? "PUT" : "POST" }); await refreshPlayback(); } catch (error) { setStatus(error.message, "error"); } }

function meetBroadcast(message) { if (meetChannel) meetChannel.postMessage({ ...message, sender: state.meet.memberId }); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]); }
function renderMeet() { const { meet } = state; $("#room-name").textContent = meet.roomName || "No room yet"; $("#room-status").textContent = meet.roomId ? `${Object.keys(meet.members).length} listener${Object.keys(meet.members).length === 1 ? "" : "s"} tuned in` : "Create a room to begin"; $("#room-form").hidden = Boolean(meet.roomId); $("#room-content").hidden = !meet.roomId; $("#copy-room-button").disabled = !meet.roomId; $("#people-list").innerHTML = Object.values(meet.members).map((member) => `<span class="person-pill"><span>${member.id === meet.hostId ? "HOST" : member.name === meet.memberName ? "YOU" : ""}</span>${escapeHtml(member.name)}</span>`).join(""); $("#chat-log").innerHTML = meet.messages.map((message) => `<p class="chat-message"><strong>${escapeHtml(message.name)}</strong><span>${escapeHtml(message.text)}</span></p>`).join(""); $("#chat-log").scrollTop = $("#chat-log").scrollHeight; }
function updateSharedTrack(track) { $("#shared-track").textContent = track ? track.name : "Waiting for the host to play a song"; $("#shared-artist").textContent = track ? `${track.artist} ${track.playing ? "is playing now" : "is paused"}` : "Anyone in the room can chat while they listen."; }
function meetPublishTrack() { if (state.meet.roomId && state.lastTrack) meetBroadcast({ type: "track", track: { name: $("#track-title").textContent, artist: $("#track-artist").textContent, playing: state.isPlaying } }); }
function applyMeetRole() { const guest = state.meet.roomId && !state.meet.isHost; $("#connect-button").disabled = Boolean(guest); $("#connect-button").textContent = guest ? "Host connects Spotify" : state.token ? "Spotify connected" : "▶ Tune into Spotify"; $("#setup-note").textContent = guest ? "The room host supplies the shared Spotify signal. You can join without an account." : state.token ? "Your session is stored only in this browser tab." : "Add your Spotify Client ID in app.js to begin."; }
function joinMeet(roomId, roomName = "Shared room") { state.meet.roomId = roomId; state.meet.roomName = roomName; const params = new URLSearchParams(window.location.search); state.meet.hostId = localStorage.getItem(`airwave-host-${roomId}`) || state.meet.memberId; state.meet.isHost = params.get("host") === "1" || state.meet.hostId === state.meet.memberId; localStorage.setItem(`airwave-host-${roomId}`, state.meet.hostId); const savedMessages = localStorage.getItem(`airwave-messages-${roomId}`); if (savedMessages) state.meet.messages = JSON.parse(savedMessages); meetChannel = new BroadcastChannel(`airwave-meet-${roomId}`); meetChannel.onmessage = ({ data }) => { if (data.sender === state.meet.memberId) return; if (data.type === "hello") { state.meet.members[data.member.id] = data.member; meetBroadcast({ type: "member", member: { id: state.meet.memberId, name: state.meet.memberName } }); renderMeet(); } if (data.type === "member") { state.meet.members[data.member.id] = data.member; renderMeet(); } if (data.type === "leave") { delete state.meet.members[data.id]; if (data.id === state.meet.hostId) { state.meet.hostId = Object.keys(state.meet.members)[0] || state.meet.memberId; state.meet.isHost = state.meet.hostId === state.meet.memberId; localStorage.setItem(`airwave-host-${roomId}`, state.meet.hostId); meetBroadcast({ type: "host", hostId: state.meet.hostId }); applyMeetRole(); } renderMeet(); } if (data.type === "host") { state.meet.hostId = data.hostId; state.meet.isHost = state.meet.hostId === state.meet.memberId; applyMeetRole(); renderMeet(); } if (data.type === "message") { state.meet.messages.push(data.message); localStorage.setItem(`airwave-messages-${roomId}`, JSON.stringify(state.meet.messages.slice(-50))); renderMeet(); } if (data.type === "track") updateSharedTrack(data.track); }; state.meet.members[state.meet.memberId] = { id: state.meet.memberId, name: state.meet.memberName }; meetBroadcast({ type: "hello", member: { id: state.meet.memberId, name: state.meet.memberName } }); applyMeetRole(); renderMeet(); }
function createMeetRoom() { const roomName = $("#room-input").value.trim() || "Late night FM"; const roomId = Math.random().toString(36).slice(2, 8); localStorage.setItem(`airwave-room-name-${roomId}`, roomName); localStorage.setItem(`airwave-host-${roomId}`, state.meet.memberId); const url = new URL(window.location.href); url.searchParams.set("room", roomId); url.searchParams.set("name", roomName); url.searchParams.set("host", "1"); history.replaceState({}, "", url); joinMeet(roomId, roomName); }
function sendMeetMessage(event) { event.preventDefault(); const input = $("#chat-input"); const text = input.value.trim(); if (!text || !state.meet.roomId) return; const message = { name: state.meet.memberName, text }; state.meet.messages.push(message); localStorage.setItem(`airwave-messages-${state.meet.roomId}`, JSON.stringify(state.meet.messages.slice(-50))); meetBroadcast({ type: "message", message }); input.value = ""; renderMeet(); }
function initMeet() { const params = new URLSearchParams(window.location.search); const roomId = params.get("room"); if (roomId) joinMeet(roomId, params.get("name") || localStorage.getItem(`airwave-room-name-${roomId}`) || "Shared room"); $("#create-room-button").addEventListener("click", createMeetRoom); $("#chat-form").addEventListener("submit", sendMeetMessage); $("#copy-room-button").addEventListener("click", async () => { const url = new URL(window.location.href); url.searchParams.delete("host"); await navigator.clipboard.writeText(url); $("#room-status").textContent = "Guest link copied"; }); window.addEventListener("beforeunload", () => meetBroadcast({ type: "leave", id: state.meet.memberId })); }

$("#connect-button").addEventListener("click", connect); $("#refresh-button").addEventListener("click", refreshPlayback); $("#pause-button").addEventListener("click", () => controlPlayback(state.isPlaying ? "pause" : "play")); $("#radio-previous-button").addEventListener("click", () => controlPlayback("previous")); $("#radio-next-button").addEventListener("click", () => controlPlayback("next"));
setInterval(tick, 250); setInterval(refreshPlayback, 5000); initMeet();
(async function init() { try { await finishLogin(); } catch (error) { setStatus(error.message, "error"); } if (state.token) { $("#connect-button").textContent = "Spotify connected"; $("#setup-note").textContent = "Your session is stored only in this browser tab."; refreshPlayback(); } })();