const CLIENT_ID = "f9b69808a4f64f299c26b42bbe1c80ef";
const REDIRECT_URI = window.location.origin + window.location.pathname;
const SCOPES = "streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state";
const API_BASE = "https://api.spotify.com/v1";

const $ = (selector) => document.querySelector(selector);
const state = { token: sessionStorage.getItem("airwave_token"), refreshToken: sessionStorage.getItem("airwave_refresh"), expiresAt: Number(sessionStorage.getItem("airwave_expires") || 0), accountProduct: sessionStorage.getItem("airwave_product"), verifier: null, lastTrack: null, lastTrackUri: null, progress: 0, duration: 0, isPlaying: false, player: null, playerDeviceId: null, timer: null, genreCache: {}, media: { stream: null, calls: {}, remoteStreams: {} }, meet: { roomId: null, roomName: null, hostId: null, peerId: null, peer: null, connections: {}, isHost: true, sharedTrack: null, turnOrder: [], turnIndex: 0, memberId: crypto.randomUUID(), memberName: `Guest ${Math.floor(Math.random() * 90 + 10)}`, members: {}, messages: [] } };
let meetChannel;

function base64Url(bytes) { return btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""); }
async function sha256(value) { return crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); }
function randomString(length) { const bytes = new Uint8Array(length); crypto.getRandomValues(bytes); return base64Url(bytes); }

async function connect() {
  if (CLIENT_ID === "YOUR_SPOTIFY_CLIENT_ID") { setStatus("Add your Spotify Client ID in app.js", "error"); return; }
  sessionStorage.setItem("airwave_return_url", window.location.href);
  state.verifier = randomString(64); sessionStorage.setItem("airwave_verifier", state.verifier);
  const challenge = base64Url(await sha256(state.verifier)); const authState = randomString(24); sessionStorage.setItem("airwave_state", authState);
  const params = new URLSearchParams({ client_id: CLIENT_ID, response_type: "code", redirect_uri: REDIRECT_URI, scope: SCOPES, state: authState, code_challenge_method: "S256", code_challenge: challenge });
  window.location.assign(`https://accounts.spotify.com/authorize?${params}`);
}

async function finishLogin() {
  const params = new URLSearchParams(window.location.search); const code = params.get("code");
  if (!code) return;
  if (params.get("state") !== sessionStorage.getItem("airwave_state")) throw new Error("Spotify authorization state did not match.");
  const verifier = sessionStorage.getItem("airwave_verifier"); const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: CLIENT_ID, grant_type: "authorization_code", code, redirect_uri: REDIRECT_URI, code_verifier: verifier }) });
  if (!response.ok) throw new Error("Spotify could not finish the connection.");
  const data = await response.json(); storeToken(data); const returnUrl = sessionStorage.getItem("airwave_return_url") || REDIRECT_URI; sessionStorage.removeItem("airwave_return_url"); window.history.replaceState({}, "", returnUrl); window.location.hash = "connected";
}
function storeToken(data) { state.token = data.access_token; state.refreshToken = data.refresh_token || state.refreshToken; state.expiresAt = Date.now() + (data.expires_in * 1000) - 60000; sessionStorage.setItem("airwave_token", state.token); sessionStorage.setItem("airwave_expires", state.expiresAt); if (state.refreshToken) sessionStorage.setItem("airwave_refresh", state.refreshToken); }
async function refreshToken() { if (!state.refreshToken) throw new Error("Your Spotify session expired. Reconnect Spotify."); const response = await fetch("https://accounts.spotify.com/api/token", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: CLIENT_ID, grant_type: "refresh_token", refresh_token: state.refreshToken }) }); if (!response.ok) throw new Error("Your Spotify session expired. Reconnect Spotify."); storeToken(await response.json()); }
async function api(path, options = {}) { if (!state.token) throw new Error("Connect Spotify to continue."); if (Date.now() > state.expiresAt) await refreshToken(); const headers = { Authorization: `Bearer ${state.token}` }; if (options.body) headers["Content-Type"] = "application/json"; let response = await fetch(API_BASE + path, { ...options, headers }); if (response.status === 401 && state.refreshToken) { await refreshToken(); headers.Authorization = `Bearer ${state.token}`; response = await fetch(API_BASE + path, { ...options, headers }); } if (response.status === 204) return null; if (response.status === 401) throw new Error("Your Spotify session expired. Reconnect Spotify."); if (response.status === 403) throw new Error("Spotify playback control needs a Premium account and an active device."); if (!response.ok) throw new Error("Spotify playback is unavailable right now."); return response.json(); }
async function checkPremium() { const profile = await api("/me"); state.accountProduct = profile.product; sessionStorage.setItem("airwave_product", profile.product || ""); if (profile.product !== "premium") throw new Error("Airwave playback requires Spotify Premium. You can still join chat and camera."); return profile; }

function setupSpotifyPlayer() { if (!window.spotifySdkReady || !state.token || state.accountProduct !== "premium" || state.player) return; state.player = new Spotify.Player({ name: "Airwave FM", getOAuthToken: (callback) => callback(state.token), volume: 0.8 }); state.player.addListener("ready", ({ device_id }) => { state.playerDeviceId = device_id; setStatus("Airwave player ready", "success"); updateTurnControls(); if (!state.meet.isHost && state.meet.sharedTrack) syncSharedTrack(); }); state.player.addListener("player_state_changed", (playerState) => { if (!playerState) return; updateTrack({ item: playerState.track_window.current_track, progress_ms: playerState.position, is_playing: !playerState.paused, device: { name: "Airwave FM" } }); }); state.player.addListener("initialization_error", () => { setStatus("Airwave playback could not start in this browser.", "error"); updateTurnControls(); }); state.player.addListener("authentication_error", () => { setStatus("Spotify authorization expired. Reconnect Spotify.", "error"); updateTurnControls(); }); state.player.connect(); }
function currentTurnId() { return state.meet.turnOrder[state.meet.turnIndex % Math.max(1, state.meet.turnOrder.length)]; }
function broadcastTurnState() { meetBroadcast({ type: "turnState", order: state.meet.turnOrder, index: state.meet.turnIndex }); updateTurnControls(); }
function updateTurnControls() { const currentId = currentTurnId(); const isMyTurn = Boolean(currentId) && currentId === state.meet.memberId; const currentMember = state.meet.members[currentId]; const hostReady = !state.meet.isHost || Boolean(state.token && state.playerDeviceId); $("#turn-status").textContent = currentId ? isMyTurn ? state.meet.isHost && !hostReady ? "Connect Spotify to start the room" : "Your turn: choose a genre" : `${currentMember?.name || "Another listener"} is choosing` : "Waiting for the host to set the turn"; $("#random-track-button").textContent = !isMyTurn ? "Waiting for turn" : state.meet.isHost && !hostReady ? "Connect Spotify first" : state.meet.isHost ? "Play genre" : "Choose genre"; $("#random-track-button").disabled = !isMyTurn || !hostReady; }
async function playRandomGenre(genre = $("#genre-select").value, advanceTurn = false) { if (!state.token) { setStatus("Connect Spotify to play music in Airwave.", "error"); return; } if (state.accountProduct !== "premium") { setStatus("Airwave playback requires Spotify Premium.", "error"); return; } if (!state.playerDeviceId) { setStatus("The Airwave player is still getting ready.", "error"); return; } try { setStatus(`Finding a random ${genre} track...`); let tracks = state.genreCache[genre]; if (!tracks) { const offset = Math.floor(Math.random() * 951); const results = await api(`/search?q=${encodeURIComponent(`genre:"${genre}"`)}&type=track&limit=50&offset=${offset}`); tracks = results.tracks.items.filter((track) => track.is_playable !== false); state.genreCache[genre] = tracks; } if (!tracks.length) throw new Error(`No playable ${genre} tracks were found.`); const track = tracks[Math.floor(Math.random() * tracks.length)]; await api(`/me/player/play?device_id=${encodeURIComponent(state.playerDeviceId)}`, { method: "PUT", body: JSON.stringify({ uris: [track.uri], position_ms: 0 }) }); meetBroadcast({ type: "track", track: { name: track.name, artist: track.artists.map((artist) => artist.name).join(", "), playing: true, uri: track.uri, progressMs: 0, durationMs: track.duration_ms, sentAt: Date.now() } }); setStatus(`Random ${genre} track is on air`, "success"); if (advanceTurn && state.meet.turnOrder.length) { state.meet.turnIndex = (state.meet.turnIndex + 1) % state.meet.turnOrder.length; broadcastTurnState(); } } catch (error) { setStatus(error.message, "error"); } }
function chooseGenre() { const currentId = currentTurnId(); if (currentId !== state.meet.memberId) return; const genre = $("#genre-select").value; if (state.meet.isHost) playRandomGenre(genre, true); else meetBroadcast({ type: "genreRequest", memberId: state.meet.memberId, genre }); }

async function refreshPlayback() {
  if (!state.token) return; setStatus("Scanning the airwaves...");
  try { const [playing, queue] = await Promise.all([api("/me/player/currently-playing"), api("/me/player/queue")]); updateTrack(playing); updateQueue(queue); } catch (error) { setStatus(error.message, "error"); }
}
function updateTrack(data) {
  if (!data || !data.item || data.item.type !== "track") { $("#track-title").textContent = "Nothing is playing yet"; $("#track-artist").textContent = "Start a song in Spotify and refresh the dial."; $("#track-album").textContent = ""; $("#radio-track-title").textContent = "AIRWAVE FM"; $("#radio-track-artist").textContent = "READY FOR A SIGNAL"; setStatus("Waiting for a signal"); return; }
  const track = data.item; state.progress = data.progress_ms || 0; state.duration = track.duration_ms || 0; state.isPlaying = Boolean(data.is_playing); state.lastTrack = track.id; state.lastTrackUri = track.uri; const artists = track.artists.map((artist) => artist.name).join(", "); $("#track-title").textContent = track.name; $("#track-artist").textContent = artists; $("#radio-track-title").textContent = track.name; $("#radio-track-artist").textContent = artists; $("#track-album").textContent = track.album.name; $("#device-name").textContent = data.device?.name || "Spotify device"; $("#album-art").innerHTML = track.album.images?.[0] ? `<img src="${track.album.images[0].url}" alt="${track.album.name} album artwork">` : '<span class="album-placeholder">&#9835;</span>'; $("#connection-label").textContent = "ON AIR"; document.body.classList.add("connected"); setStatus(state.isPlaying ? "Now transmitting" : "Paused in Spotify", "success"); updateProgress(); meetPublishTrack(); }
function updateQueue(data) { const item = data?.queue?.[0]; $("#next-track").textContent = item ? `Next up: ${item.name} / ${item.artists?.[0]?.name || "Unknown artist"}` : "Next up: queue is empty"; }
function updateProgress() { const percent = state.duration ? Math.min(100, (state.progress / state.duration) * 100) : 0; $("#progress-bar").style.width = `${percent}%`; $("#track-time").textContent = `${formatTime(state.progress)} / ${formatTime(state.duration)}`; }
function formatTime(ms) { const seconds = Math.floor(ms / 1000); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; }
function setStatus(message, type = "idle") { $("#status-message").textContent = message; $("#status-message").style.color = type === "error" ? "var(--rust-dark)" : type === "success" ? "var(--green)" : ""; }
function tick() { if (state.isPlaying && state.progress < state.duration) { state.progress += 250; updateProgress(); } }
async function controlPlayback(action) { if (!state.token) { setStatus("Connect Spotify before controlling playback.", "error"); return; } try { setStatus("Sending command..."); const endpoint = action === "play" ? "/me/player/play" : action === "pause" ? "/me/player/pause" : `/me/player/${action}`; await api(endpoint, { method: action === "play" || action === "pause" ? "PUT" : "POST" }); await refreshPlayback(); } catch (error) { setStatus(error.message, "error"); } }

function meetBroadcast(message) { const payload = { ...message, sender: state.meet.memberId }; if (meetChannel) meetChannel.postMessage(payload); Object.values(state.meet.connections).forEach((connection) => { if (connection.open) connection.send(payload); }); }
function mediaTile(id, name, stream, local = false) { let tile = document.querySelector(`[data-video-id="${id}"]`); if (!tile) { tile = document.createElement("div"); tile.className = "video-tile"; tile.dataset.videoId = id; tile.innerHTML = `<video autoplay playsinline ${local ? "muted" : ""}></video><span>${escapeHtml(name)}${local ? " (you)" : ""}</span>`; $("#video-grid").appendChild(tile); } const video = tile.querySelector("video"); if (video.srcObject !== stream) video.srcObject = stream; $("#video-empty").hidden = Boolean(document.querySelector(".video-tile")); }
function receiveMedia(id, name, stream) { state.media.remoteStreams[id] = stream; mediaTile(id, name, stream); }
function callPeer(peerId, name) { if (!state.media.stream || !state.meet.peer) return; const call = state.meet.peer.call(peerId, state.media.stream, { metadata: { name: state.meet.memberName } }); state.media.calls[peerId] = call; call.on("stream", (stream) => receiveMedia(peerId, name, stream)); }
async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) { setStatus("Camera access requires HTTPS or localhost.", "error"); return; } try { state.media.stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); mediaTile(state.meet.memberId, state.meet.memberName, state.media.stream, true); $("#camera-button").textContent = "Leave camera"; $("#mic-button").disabled = false; $("#video-button").disabled = false; if (state.meet.isHost) Object.keys(state.meet.connections).forEach((id) => callPeer(id, state.meet.members[id]?.name || "Listener")); else { const hostPeer = new URLSearchParams(window.location.search).get("peer"); if (hostPeer) callPeer(hostPeer, "Host"); } } catch (error) { setStatus("Camera or microphone permission was declined.", "error"); } }
function stopCamera() { if (!state.media.stream) return; state.media.stream.getTracks().forEach((track) => track.stop()); state.media.stream = null; Object.values(state.media.calls).forEach((call) => call.close()); state.media.calls = {}; const tile = document.querySelector(`[data-video-id="${state.meet.memberId}"]`); tile?.remove(); $("#video-empty").hidden = !document.querySelector(".video-tile"); $("#camera-button").textContent = "Join camera"; $("#mic-button").disabled = true; $("#video-button").disabled = true; }
function toggleMicrophone() { const track = state.media.stream?.getAudioTracks()[0]; if (!track) return; track.enabled = !track.enabled; $("#mic-button").textContent = track.enabled ? "🎙" : "🔇"; $("#mic-button").setAttribute("aria-label", track.enabled ? "Mute microphone" : "Unmute microphone"); }
function toggleVideo() { const track = state.media.stream?.getVideoTracks()[0]; if (!track) return; track.enabled = !track.enabled; $("#video-button").textContent = track.enabled ? "📹" : "🚫"; $("#video-button").setAttribute("aria-label", track.enabled ? "Turn camera off" : "Turn camera on"); }
function handlePeerMessage(data) { if (!data || data.sender === state.meet.memberId) return; if (data.type === "hello") { state.meet.members[data.member.id] = data.member; if (state.meet.isHost && !state.meet.turnOrder.includes(data.member.id)) { state.meet.turnOrder.push(data.member.id); broadcastTurnState(); } meetBroadcast({ type: "member", member: { id: state.meet.memberId, name: state.meet.memberName } }); if (state.meet.isHost) { const connection = state.meet.connections[data.sender]; if (connection?.open) connection.send({ type: "history", messages: state.meet.messages, order: state.meet.turnOrder, index: state.meet.turnIndex, sender: state.meet.memberId }); } renderMeet(); } if (data.type === "member") { state.meet.members[data.member.id] = data.member; renderMeet(); } if (data.type === "turnState") { state.meet.turnOrder = data.order || []; state.meet.turnIndex = data.index || 0; updateTurnControls(); } if (data.type === "genreRequest" && state.meet.isHost && data.memberId === currentTurnId()) playRandomGenre(data.genre, true); if (data.type === "leave") { delete state.meet.members[data.id]; state.meet.turnOrder = state.meet.turnOrder.filter((id) => id !== data.id); if (state.meet.turnIndex >= state.meet.turnOrder.length) state.meet.turnIndex = 0; if (state.meet.isHost) broadcastTurnState(); renderMeet(); } if (data.type === "message") { state.meet.messages.push(data.message); localStorage.setItem(`airwave-messages-${state.meet.roomId}`, JSON.stringify(state.meet.messages.slice(-50))); renderMeet(); } if (data.type === "track") updateSharedTrack(data.track); if (data.type === "history") { state.meet.messages = data.messages || []; state.meet.turnOrder = data.order || state.meet.turnOrder; state.meet.turnIndex = data.index || 0; renderMeet(); } }
function registerPeerConnection(connection) { state.meet.connections[connection.peer] = connection; connection.on("data", handlePeerMessage); connection.on("open", () => { if (state.media.stream && state.meet.isHost) callPeer(connection.peer, state.meet.members[connection.peer]?.name || "Listener"); }); connection.on("close", () => { delete state.meet.connections[connection.peer]; delete state.meet.members[connection.peer]; state.media.calls[connection.peer]?.close(); delete state.media.calls[connection.peer]; document.querySelector(`[data-video-id="${connection.peer}"]`)?.remove(); renderMeet(); }); }
function setupMeetPeer() { if (!window.Peer) { setStatus("Room networking is unavailable. Deploy the app over HTTPS and try again.", "error"); return; } const params = new URLSearchParams(window.location.search); state.meet.peer = new Peer(); state.meet.peer.on("open", (peerId) => { state.meet.peerId = peerId; const url = new URL(window.location.href); url.searchParams.set("peer", peerId); history.replaceState({}, "", url); $("#copy-room-button").disabled = false; setStatus(state.meet.isHost ? "Room ready to share" : "Connected to the host", "success"); if (!state.meet.isHost && params.get("peer")) { const connection = state.meet.peer.connect(params.get("peer")); registerPeerConnection(connection); connection.on("open", () => connection.send({ type: "hello", member: { id: state.meet.memberId, name: state.meet.memberName }, sender: state.meet.memberId })); } }); state.meet.peer.on("connection", registerPeerConnection); state.meet.peer.on("call", (call) => { call.answer(state.media.stream || undefined); state.media.calls[call.peer] = call; call.on("stream", (stream) => receiveMedia(call.peer, call.metadata?.name || "Listener", stream)); }); state.meet.peer.on("error", () => setStatus("Could not connect this room. Check the invite link and try again.", "error")); }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]); }
function renderMeet() { const { meet } = state; $("#room-name").textContent = meet.roomName || "No room yet"; $("#room-status").textContent = meet.roomId ? `${Object.keys(meet.members).length} listener${Object.keys(meet.members).length === 1 ? "" : "s"} tuned in` : "Create a room to begin"; $("#room-form").hidden = Boolean(meet.roomId); $("#room-content").hidden = !meet.roomId; $("#copy-room-button").disabled = !meet.roomId; $("#people-list").innerHTML = Object.values(meet.members).map((member) => `<span class="person-pill"><span>${member.id === meet.hostId ? "HOST" : member.name === meet.memberName ? "YOU" : ""}</span>${escapeHtml(member.name)}</span>`).join(""); $("#chat-log").innerHTML = meet.messages.map((message) => `<p class="chat-message"><strong>${escapeHtml(message.name)}</strong><span>${escapeHtml(message.text)}</span></p>`).join(""); $("#chat-log").scrollTop = $("#chat-log").scrollHeight; updateTurnControls(); }
function updateSharedTrack(track) { const trackChanged = state.meet.sharedTrack?.uri !== track?.uri; state.meet.sharedTrack = track; $("#shared-track").textContent = track ? track.name : "Waiting for the host to play a song"; $("#shared-artist").textContent = track ? `${track.artist} ${track.playing ? "is playing now" : "is paused"}` : "Anyone in the room can chat while they listen."; const link = $("#shared-track-link"); const sync = $("#sync-track-button"); if (track?.uri) { const trackId = track.uri.split(":").pop(); link.href = `https://open.spotify.com/track/${encodeURIComponent(trackId)}`; link.hidden = false; sync.hidden = state.meet.isHost; if (trackChanged && !state.meet.isHost && state.token && state.playerDeviceId) syncSharedTrack(); } else { link.hidden = true; sync.hidden = true; } }
function meetPublishTrack() { if (state.meet.roomId && state.meet.isHost && state.lastTrack) meetBroadcast({ type: "track", track: { name: $("#track-title").textContent, artist: $("#track-artist").textContent, playing: state.isPlaying, uri: state.lastTrackUri, progressMs: state.progress, durationMs: state.duration, sentAt: Date.now() } }); }
async function syncSharedTrack() { const track = state.meet.sharedTrack; if (!track?.uri) return; if (!state.token) { setStatus("Connect Spotify first to sync this song.", "error"); return; } const positionMs = Math.min(track.durationMs || track.progressMs || 0, (track.progressMs || 0) + Math.max(0, Date.now() - (track.sentAt || Date.now()))); try { setStatus("Syncing your Spotify..."); await api("/me/player/play", { method: "PUT", body: JSON.stringify({ uris: [track.uri], position_ms: Math.floor(positionMs) }) }); setStatus("Synced to the room", "success"); } catch (error) { setStatus(error.message, "error"); } }
function applyMeetRole() { const guest = state.meet.roomId && !state.meet.isHost; $("#connect-button").disabled = false; $("#connect-button").textContent = guest ? state.token ? "Spotify connected" : "Connect Spotify to sync" : state.token ? "Spotify connected" : "▶ Tune into Spotify"; $("#setup-note").textContent = guest ? "Connect your Spotify account to start the shared song at the host's position. Premium and an active device are required." : state.token ? "Your session is stored only in this browser tab." : "Add your Spotify Client ID in app.js to begin."; if (state.meet.sharedTrack) updateSharedTrack(state.meet.sharedTrack); }
function joinMeet(roomId, roomName = "Shared room") { state.meet.roomId = roomId; state.meet.roomName = roomName; const params = new URLSearchParams(window.location.search); state.meet.hostId = localStorage.getItem(`airwave-host-${roomId}`) || state.meet.memberId; state.meet.isHost = params.get("host") === "1" || (!params.get("peer") && state.meet.hostId === state.meet.memberId); localStorage.setItem(`airwave-host-${roomId}`, state.meet.hostId); const savedMessages = localStorage.getItem(`airwave-messages-${roomId}`); if (savedMessages) state.meet.messages = JSON.parse(savedMessages); meetChannel = new BroadcastChannel(`airwave-meet-${roomId}`); meetChannel.onmessage = ({ data }) => { if (data.sender === state.meet.memberId) return; if (data.type === "hello") { state.meet.members[data.member.id] = data.member; if (state.meet.isHost && !state.meet.turnOrder.includes(data.member.id)) { state.meet.turnOrder.push(data.member.id); broadcastTurnState(); } meetBroadcast({ type: "member", member: { id: state.meet.memberId, name: state.meet.memberName } }); renderMeet(); } if (data.type === "member") { state.meet.members[data.member.id] = data.member; renderMeet(); } if (data.type === "turnState") { state.meet.turnOrder = data.order || []; state.meet.turnIndex = data.index || 0; updateTurnControls(); } if (data.type === "genreRequest" && state.meet.isHost && data.memberId === currentTurnId()) playRandomGenre(data.genre, true); if (data.type === "leave") { delete state.meet.members[data.id]; state.meet.turnOrder = state.meet.turnOrder.filter((id) => id !== data.id); if (state.meet.turnIndex >= state.meet.turnOrder.length) state.meet.turnIndex = 0; if (state.meet.isHost) broadcastTurnState(); renderMeet(); } if (data.type === "host") { state.meet.hostId = data.hostId; state.meet.isHost = state.meet.hostId === state.meet.memberId; applyMeetRole(); renderMeet(); } if (data.type === "message") { state.meet.messages.push(data.message); localStorage.setItem(`airwave-messages-${roomId}`, JSON.stringify(state.meet.messages.slice(-50))); renderMeet(); } if (data.type === "track") updateSharedTrack(data.track); }; state.meet.members[state.meet.memberId] = { id: state.meet.memberId, name: state.meet.memberName }; state.meet.turnOrder = state.meet.isHost ? [state.meet.memberId] : []; setupMeetPeer(); meetBroadcast({ type: "hello", member: { id: state.meet.memberId, name: state.meet.memberName } }); applyMeetRole(); renderMeet(); }
function createMeetRoom() { const roomName = $("#room-input").value.trim() || "Late night FM"; const roomId = Math.random().toString(36).slice(2, 8); localStorage.setItem(`airwave-room-name-${roomId}`, roomName); localStorage.setItem(`airwave-host-${roomId}`, state.meet.memberId); const url = new URL(window.location.href); url.searchParams.set("room", roomId); url.searchParams.set("name", roomName); url.searchParams.set("host", "1"); history.replaceState({}, "", url); joinMeet(roomId, roomName); }
function sendMeetMessage(event) { event.preventDefault(); const input = $("#chat-input"); const text = input.value.trim(); if (!text || !state.meet.roomId) return; const message = { name: state.meet.memberName, text }; state.meet.messages.push(message); localStorage.setItem(`airwave-messages-${state.meet.roomId}`, JSON.stringify(state.meet.messages.slice(-50))); meetBroadcast({ type: "message", message }); input.value = ""; renderMeet(); }
function initMeet() { const params = new URLSearchParams(window.location.search); const roomId = params.get("room"); if (roomId) joinMeet(roomId, params.get("name") || localStorage.getItem(`airwave-room-name-${roomId}`) || "Shared room"); $("#create-room-button").addEventListener("click", createMeetRoom); $("#chat-form").addEventListener("submit", sendMeetMessage); $("#camera-button").addEventListener("click", () => state.media.stream ? stopCamera() : startCamera()); $("#mic-button").addEventListener("click", toggleMicrophone); $("#video-button").addEventListener("click", toggleVideo); $("#sync-track-button").addEventListener("click", syncSharedTrack); $("#random-track-button").addEventListener("click", chooseGenre); $("#copy-room-button").addEventListener("click", async () => { const url = new URL(window.location.href); url.searchParams.delete("host"); await navigator.clipboard.writeText(url); $("#room-status").textContent = "Guest link copied"; }); window.addEventListener("beforeunload", () => { stopCamera(); meetBroadcast({ type: "leave", id: state.meet.memberId }); }); }

$("#connect-button").addEventListener("click", connect); $("#refresh-button").addEventListener("click", refreshPlayback); $("#pause-button").addEventListener("click", () => controlPlayback(state.isPlaying ? "pause" : "play")); $("#radio-previous-button").addEventListener("click", () => controlPlayback("previous")); $("#radio-next-button").addEventListener("click", () => controlPlayback("next"));
setInterval(tick, 250); setInterval(refreshPlayback, 5000); setInterval(() => { if (state.meet.isHost) meetPublishTrack(); }, 1000); initMeet();
window.addEventListener("spotify-sdk-ready", setupSpotifyPlayer);
(async function init() { try { await finishLogin(); if (state.token) { await checkPremium(); applyMeetRole(); setupSpotifyPlayer(); refreshPlayback(); } } catch (error) { setStatus(error.message, "error"); applyMeetRole(); } })();